ALTER TABLE users ADD COLUMN email VARCHAR(255) UNIQUE;
ALTER TABLE users ALTER COLUMN phone_number DROP NOT NULL;

ALTER TABLE user_otps ADD COLUMN email VARCHAR(255);
ALTER TABLE user_otps ALTER COLUMN phone_number DROP NOT NULL;
