spring.application.name=nura-backend

# Expose Spring Boot Actuator Web health endpoint for health checks
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always
